config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :recruits, only: [:index, :show, :edit, :create, :destroy, :update, :new] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :favorites, only: [:create, :destroy]
    resources :recruit_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get 'favorites' => 'users#favorites', as: 'favorites'
  end
  resource :relationships, only: [:create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
belongs_to :recruit
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
   before_action :authenticate_user!

  def create
    @recruit = Recruit.find(params[:recruit_id])
    favorite = @recruit.favorites.new(user_id: current_user.id)
    favorite.save
    # redirect_to request.referer
    @recruit.create_notification_favorite!(current_user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.js
    end
    redirect_to request.referer
  end

  def destroy
    @recruit = Recruit.find(params[:recruit_id])
    favorite = @recruit.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    redirect_to request.referer
  end
  
  def index
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if recruit.favorited_by?(current_user) %>
<%= link_to recruit_favorite_path(recruit, recruit.favorites.find_by(user_id: current_user.id)), method: :delete, remote: true do %>
<p>
  <i>応募</i>
  <%= recruit.favorites.count %>
  <% end %>
</p>
<% else %>
<p>
  <%= link_to recruit_favorites_path(recruit), method: :post, remote: true do %>
  <i>応募</i>
  <%= recruit.favorites.count %><% end %>
</p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-btn_<%= @recruit.id %>').html("<%= j(render partial: 'favorites/favorite-btn', locals: {recruit: @recruit}) %>");

app/views/favorites/destroy.js.erb
$('#favorite-btn_<%= @recruit.id %>').html("<%= j(render partial: 'favorites/favorite-btn', locals: {recruit: @recruit}) %>");