config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :recruits, only: [:index, :show, :edit, :create, :destroy, :update, :new] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :favorites, only: [:create, :destroy]
    resources :recruit_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get 'favorites' => 'users#favorites', as: 'favorites'
  end
  resource :relationships, only: [:create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }
  belongs_to :visitor, class_name: "User", optional: true
  belongs_to :visited, class_name: "User", optional: true
  belongs_to :recruit, optional: true
  belongs_to :recruit_comment, optional: true
  
  validates :visitor_id, presence: true
  validates :visited_id, presence: true
  ACTION_VALUES = ["favorite", "follow", "recruit_comment"]
  validates :action,  presence: true, inclusion: {in:ACTION_VALUES}
  validates :checked, inclusion: {in: [true,false]}



end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    
    def index
        @notifications2 = Notification.where(visited_id: current_user.id).order('created_at')
        #通知画面を開くとcheckedをtrueにして通知確認済にする
        @notifications2.where(checked: false).each do |notification|
          notification.update_attributes(checked: true)
        end
    end

    def destroy
        @notifications =current_user.passive_notifications.destroy_all
        redirect_to notifications_path
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    #通知を送ってきたユーザーを取得
    @visitor = notification.visitor
    #コメントの内容を通知に表示する
    @recruit_comment = nil
    @visitor_comment = notification.recruit_comment_id
    # notification.actionがfollowかlikeかcommentかで処理を変える
    case notification.action
    when 'follow'
      #aタグで通知を作成したユーザーshowのリンクを作成
      tag.a(notification.visitor.name, href: user_path(@visitor)) + 'があなたをフォローしました'
    when 'favorite'
      tag.a(notification.visitor.name, href: user_path(@visitor)) + 'が' + tag.a('あなたの投稿', href: recruit_path(notification.recruit_id)) + 'に応募しました'
    when 'recruit_comment' then
      #コメントの内容と投稿のタイトルを取得
      @recruit_comment = RecruitComment.find_by(id: @visitor_comment)
      @recruit_comment_commrnt =@recruit_comment.comment
      @recruit_title =@recruit_comment.recruit.title
      tag.a(@visitor.name, href: user_path(@visitor)) + 'が' + tag.a("#{@recruit_title}", href: recruit_path(notification.recruit_id)) + 'にコメントしました'
    end
  end
  
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<div class="notification-view">
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
  <br>
  <% if !@recruit_comment.nil? %>
    <p class="notification-comment"><%= @recruit_comment.comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<div class="row">
  <%= render'layouts/sidebar' %>
  <div class="col-10 background px-0">
    <div class="text-center">
      <div class="col border-bottom border-dark" style="background-color:rgba(0,0,0,0.5);">
        <h1 class="top-text">通知</h1>
      </div>
    </div>
  <div class="row justify-content-center" >
    <div class="col-6 my-3 p-1"style="border:solid 1px #DAA25A;;background-color:#FFFFF0;">
      <div class="col-6 mt-1 mx-1">
        <%= link_to "通知削除", notification_path(@notifications2), method: :delete ,class: "fas fa-trash" %>
    </div>
      <% if @notifications2.exists? %>
      <div class="notification-index">
        <%= render @notifications2 %>
      </div>
      <% else %>
        <p>通知はありません</p>
      <% end %>
    </div>
  </div>
</div>