config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :recruits, only: [:index, :show, :edit, :create, :destroy, :update, :new] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :favorites, only: [:create, :destroy]
    resources :recruit_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get 'favorites' => 'users#favorites', as: 'favorites'
  end
  resource :relationships, only: [:create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/recruit.rb
class Recruit < ApplicationRecord

  belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :recruit_comments, dependent: :destroy
	has_many :notifications, dependent: :destroy
	
  validates :date, presence:true
  validates :title, presence:true
  validates :body, presence:true
  validates :reward, presence:true
  validates :position, presence:true

  def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and recruit_id = ? and action = ? ",current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        recruit_id: id,
        visited_id: user_id,
        action: 'favorite'
      )

      if notification.visitor_id == notification.visited_id
         notification.checked = true
      end
      notification.save if notification.valid?
    end

    def create_notification_recruit_comment!(current_user, recruit_comment_id)
    #同じ投稿にコメントしているユーザーに通知を送る。（current_userと投稿ユーザーのぞく）
    temp_ids = RecruitComment.where(recruit_id: id).where.not("user_id=? or user_id=?", current_user.id,user_id).select(:user_id).distinct
    #取得したユーザー達へ通知を作成。（user_idのみ繰り返し取得）
    temp_ids.each do |temp_id|
      save_notification_recruit_comment!(current_user, recruit_comment_id, temp_id['user_id'])
    end
    #投稿者へ通知を作成
    save_notification_recruit_comment!(current_user, recruit_comment_id, user_id)
    end

    def save_notification_recruit_comment!(current_user, recruit_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      recruit_id: id,
      recruit_comment_id: recruit_comment_id,
      visited_id: visited_id,
      action: 'recruit_comment')
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
    end
  end
  

end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @recruit = Recruit.find(params[:id])
    @recruits = Recruit.all
    @user = @recruit.user
    @recruit_comment = RecruitComment.new
  end

  def index
    @recruits = Recruit.all
    @recruits = Recruit.page(params[:page]).per(10).reverse_order
    @recruit = Recruit.new
  end
  
  def new
    @recruit = Recruit.new
  end

  def create
    @recruit = Recruit.new(recruit_params)
    @recruit.user_id = current_user.id
    if @recruit.save
      redirect_to recruit_path(@recruit)
      flash[:notice] ="投稿しました"
    else
      # @recruits = Recruit.all
      render 'new'
    end
  end

  def edit
    @recruit = Recruit.find(params[:id])
    if @recruit.user_id != current_user.id
      redirect_to recruits_path
    end
  end

  def update
    @recruit = Recruit.find(params[:id])
    if @recruit.update(recruit_params)
      flash[:notice] = "You have updated recruit successfully."
      redirect_to recruit_path(@recruit.id)
    else
      render '/recruits/edit'
    end
  end

  def destroy
    @recruit = Recruit.find(params[:id])
    @recruit.destroy
    redirect_to recruits_path
  end
  
  def following
    @recruits = @recruit.where(user_id:current_user.following_user.ids)
  end

  private

  def recruit_params
    params.require(:recruit).permit(:title, :body, :position, :reward, :date )
  end

  def ensure_correct_user
    @recruit = Recruit.find(params[:id])
    unless @recruit.user == current_user
      redirect_to recruits_path
    end
  end

end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/recruits/_form.html.erb
<%= form_with model:recruit,local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputName", placeholder:""%>
  </div>

  <div class="field row">
    <%= f.label :概要 %>
    <%= f.text_field :body, autofocus: true, class:"form-control", id:"inputName", placeholder:""%>
  </div>

  <div class="field row">
    <%= f.label :場所 %>
    <%= f.text_field :position, autofocus: true, class:"form-control", id:"inputName", placeholder:""%>

  </div>

  <div class="field row">
    <%= f.label :謝礼金 %>
    <%= f.number_field :reward, autofocus: true, class:"form-control", id:"inputName", placeholder:"円"%>
  </div>
  <br>
  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/recruits/_index.html.erb
  <table class="table table-hover table-light">
  <% recruits.each do |recruit| %>
    <tbody>
      <tr>
        <td><%= link_to recruit.title, recruit_path(recruit), class: "recruit_#{recruit.id}" %></td>
        <td><%#= recruit.body %></td>
        <td>場所<%= recruit.position %></td>
        <td>報酬 <%= recruit.reward %>円</td>
        <!--<td>コメント数: <%#= recruit.recruit_comments.count %></td>-->
        <td class="favorite-btn" id="favorite-btn_<%= recruit.id %>"><%= render "favorites/favorite-btn", recruit: recruit %></td>
  <% end %>
      </tr>
    </tbody>
  </table>

app/views/recruits/_recruit_comment.html.erb
<table id="recruit_comments_<%= recruit.id %>">
  <% recruit.recruit_comments.each do |recruit_comment| %>
    <% recruit_comment_user = recruit_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(recruit_comment_user), class: "user_#{recruit_comment_user.id}" do %>
      		<%= attachment_image_tag recruit_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= recruit_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= recruit_comment.comment %></td>
    	<% if current_user == recruit_comment_user %>
      	<td><%= link_to 'Destroy', recruit_recruit_comment_path(recruit_comment.recruit_id, recruit_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model:[recruit,recruit_comment], remote: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %>
  <%= f.submit '送信'%>
<% end %>

app/views/recruits/create.js.erb
$('#favorite-btn_<%= @recruit.id %>').html("<%= j(render partial: 'recruits/recruit_comments', locals: {recruit: @recruit}) %>");

app/views/recruits/destroy.js.erb
$('#favorite-btn_<%= @recruit.id %>').html("<%= j(render partial: 'recruits/recruit_comments', locals: {recruit: @recruit}) %>");

app/views/recruits/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<% if @recruit.errors.any? %>
				<div>
					<h3 style="color: red"><%= pluralize(@recruit.errors.count, "error") %> prohibited this obj from being saved:</h3>
					<ul>
						<% @recruit.errors.full_messages.each do|message| %>
						<li style="color: red"><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<h1>Editing Recruit</h1>
			<%= form_for(@recruit) do |f| %>
				<div class="field">
					<%= f.label :title %><br>
					<%= f.text_field :title, size:"74" %>
				</div>
				<div class="field">
					<%= f.label :謝礼 %>
					<%= f.text_field :reward, class: 'col-xs-12 recruit_reward' %>
  			</div>
  			<div class="field">
    			<%= f.label :会場 %>
    			<%= f.text_field :position, class: 'col-xs-12 recruit_title' %>
    			</div>
				<div class="field">
					<%= f.label :概要 %><br>
					<%= f.text_area :body, size:"76" %>
				</div>
				<%= f.submit "Update Recruit", class:"btn btn-block btn-primary" %>
			<% end %>
			<%= link_to "Show", recruit_path(@recruit.id) %>
			<%= link_to "Back", recruits_path %>
		</div>
	</div>
</div>

app/views/recruits/index.html.erb
<div class="row">
  <%= render'layouts/sidebar' %>
  <div class="col-10 background px-0">
    <div class="text-center">
      <div class="col border-bottom border-dark" style="background-color:rgba(0,0,0,0.5);">
        <h1 class="top-text">募集一覧</h1>
      </div>
    </div>
      <%= render'layouts/timeline', recruits: @recruits %>
    </div>
  </div>
</div>

app/views/recruits/new.html.erb
<div class="row">
  <%= render'layouts/sidebar' %>
  <div class="col-10 background px-0">
    <div class="text-center">
      <div class="col border-bottom border-dark" style="background-color:rgba(0,0,0,0.5);">
        <h1 class="top-text">新規募集</h1>
      </div>
    </div>
    <div class="row justify-content-center my-3">
      <div class="col-6 border p-0" style="background-color:white;">
        <div class="write_header">
          <h2 class="p-3" style="color:white;">
            新規募集</h2>
        </div>
        
    <% if @recruit.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @recruit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
        
        <div class="write_body">
          <%= form_for @recruit,:url => {:action => :create} do |f| %>
          <div class="mt-2">
            <%= f.label :日付 %>
            <%= f.date_field :date %>
          </div>
          <div class="mt-2">
            <%= f.label :title %>
            <%= f.text_field :title,　class: "hoge", size: 30 %>
          </div>
          <div class="mt-2">
            <%= f.label :謝礼 %>
            <%= f.text_field :reward,　class: "hoge", size: 30 %>
          </div>
          <div class="mt-2">
            <%= f.label :場所 %>
            <%= f.text_field :position,　class: "hoge", size: 30 %>
          </div>
          <div class="mt-2">
            <%= f.label :概要 %><br>
            <%= f.text_area :body,　class: "hoge", size: "50x10" %>
          </div>
          <div class="tags my-2 text-center">
            <%= f.submit "登録",class: "btn btn-dark" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recruits/show.html.erb
<div class="row">
  <%= render'layouts/sidebar' %>
  <div class="col-10 background px-0">
    <div class="text-center">
      <div class="col border-bottom border-dark" style="background-color:rgba(0,0,0,0.5);">
        <h1 class="top-text">要請詳細</h1>
      </div>
    </div>
  <%= render'layouts/profile',users: @user, user: @user, recruit: @recruit %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="row mt-3">
        <div class=col>
          <div class="card">
            <div class="card-header">
              <h3><%= @recruit.title %></h3>
            </div>
            <div class="card-body">
               投稿者 ：   <%= link_to user_path(@recruit.user) do %>
          <%= attachment_image_tag(@recruit.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
              <%= @recruit.user.name %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class=col>
          <div class="card">
            <div class="card-header">
              <h3>日付</h3>
            </div>
            <div class="card-body">
              <%= @recruit.date.strftime('%Y年%m月%d日') %>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row mt-3">
        <div class=col>
          <div class="card">
            <div class="card-header">
              <h3>会場</h3>
            </div>
            <div class="card-body">
              <%= @recruit.position %>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row mt-3">
        <div class=col>
          <div class="card">
            <div class="card-header">
              <h3>謝礼</h3>
            </div>
            <div class="card-body">
              <%= @recruit.reward %> 円
            </div>
          </div>
        </div>
      </div>
      
      <div class="row mt-3">
        <div class="col">
          <div class="card">
            <div class="card-header">
              <h3>概要</h3>
            </div>
            <div class="card-body">
              <h4 class="card-title"><%= @recruit.body %></h4>
              <div class="card-text"><%#= simple_format(@diary.impression) %></div>
            </div>
          </div>
        </div>
      </div>
      
      <% if @recruit.user == current_user %>
      <div class="row mt-3">
        <div class="col text-center">
          <%= link_to '編集する', edit_recruit_path(@recruit), class: "btn btn-info" %>
          <%= link_to '消去', recruit_path(@recruit), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger"%>
        </div>
      </div>
       <% end %>
      
      
      <div class="row mt-3">
        <div class=col>
          <div class="card">
            <div class="card-header">
              <h3>応募者 <%= @recruit.favorites.count %>人</h3>
            </div>
            <div class="card-body">
              <% @recruit.favorites.each do |favorite| %>
              <div class="row my-1">
                <div class=col>
                  <%= link_to user_path(favorite.user) do %>
                  <%= attachment_image_tag favorite.user, :profile_image, format: 'jpeg'  ,class:"img-fluid rounded-circle" ,fallback: "no_image.jpg",size: "60x60"%>
                  <%= favorite.user.name%>
                  <% end %>
                </div>
              </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row mt-3">
        <div class=col>
          <div class="card">
            <div class="card-header">
              <h3>コメント <%= @recruit.recruit_comments.count %>件</h3>
              </div>
            <% @recruit.recruit_comments.each do |comment| %>
              <div class="card-body p-2">
                <div class="col-12">
                  <%= link_to user_path(comment.user) do %>
                  <%= attachment_image_tag comment.user, :profile_image, format: 'jpeg'  ,class:"img-fluid rounded-circle" ,fallback: "no_image.jpg"%>
                  <%= comment.user.name %>
                  <%end%>
                  <span class="comment-date"><%= comment.created_at.strftime('%Y/%m/%d/%H:%M') %></span>
                </div>
                <div class="col-10 border-primary"><%= simple_format(comment.comment) %></div>
                <% if comment.user_id == current_user.id %>
                <div class="col text-right">
                  <%= link_to "削除", recruit_recruit_comment_path(comment.recruit, comment), method: :delete, class: "btn btn-danger pull-right btn-sm", data: {confirm: "本当にいいですか？"} %>
                </div>
                <% end %>
              </div>
            <% end %>
            </div>
          </div>
        </div>
        <br>
        <div class="row p-0 mb-2">
          <%= form_for [@recruit, @recruit_comment] do |f| %>
          <div class="col-12 p-0">
            <%= f.text_area :comment,cols:'110', rows:'5', class: "form-control mw-100",placeholder: "コメントをここに" %><br>
            <%= f.submit "送信する", class: "btn  btn-sg btn-base-1 mt-20 pull-left" %>
          </div>
          <% end %>
        </div>
  
    </div>
  </div>
  </div>
</div>