config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :recruits, only: [:index, :show, :edit, :create, :destroy, :update, :new] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :favorites, only: [:create, :destroy]
    resources :recruit_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get 'favorites' => 'users#favorites', as: 'favorites'
  end
  resource :relationships, only: [:create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Fensers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' recruits', recruits_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
          <li class="notification"><%= link_to '通知', notifications_path, class:"btn"  %>
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle notification-circle"></i>
            <p>てすと</p>
          <% end %>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_profile.html.erb
<div class="row justify-content-center" >
	<!-- user情報 -->
	<div class="col-6 my-3 p-1"style="border:solid 1px #DAA25A;;background-color:#FFFFF0;">
		<div class="row">
	  	<div class="col-6 mt-1 mx-1">
	     <%= link_to user_path(recruit.user) do %>
	      <%= attachment_image_tag recruit.user, :profile_image, format: 'jpeg'  ,class:"img-fluid rounded-circle" ,fallback: "no_image.jpg",size: "40x40" %>
	      <%= users.name %><% end %>
	    </div>
			<!-- ログインが自分か他人か -->
	     <% if users==current_user %>
	      <div class="col-4 my-auto"><%= link_to "プロフィール編集", edit_user_path(users)%></div>
	     <% else %>
	    <div class="col-4 my-auto" id="follow_buttons_<%= user.id %>">
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', relationships_path(user_id: user.id), method: :delete,class: "btn btn-outline-warning btn-sm"%>
        <% else %>
          <%= link_to 'フォローする', relationships_path(user_id: user.id), method: :post,class: "btn btn-outline-primary btn-sm" %>
        <% end %>
	   </div>
	   		<% end %>
	  </div>
	  <div class="row my-3">
	    <div class="col text-center">フォロワー<br>
	    	<%= link_to recruit_followers_path(@recruit) do %>
	    		<%= user.followers.count %> 
	    	<% end %>
	    </div>
	    <div class="col text-center">フォロー<br>
	    	<%= link_to recruit_followings_path(@recruit) do %>
	    	<%= user.followings.count %> <% end %>
	    </div>
	    <div class="col text-center">参加履歴<br>
	    	<%= link_to user_favorites_path(user) do %>
	    	<%= user.favorites.count %> <% end %></div>
	  </div>
	</div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-2 bg-dark">
  <div class="sidebar">
    <div class="logo py-2 text-center">
      <%= link_to(root_path) do %>
      <%= image_tag 'ダウンロード.png', size: "170x60" %>
      <% end %>
    </div>
    <ul class="list-unstyled text-white text-center">
      <% if user_signed_in? %>
        <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
        <!--<li><%#= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>-->
        <li><%= link_to ' 新規募集', new_recruit_path, class: 'glyphicon glyphicon-user users' %></li>
        <li><%= link_to ' 募集一覧', recruits_path, class: 'glyphicon glyphicon-book books'%></li>
        <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <li class="notification"><%= link_to '通知', notifications_path, class:"btn"  %>
          
        <% if unchecked_notifications.any? %>
          <i class="fa fa-circle notification-circle"></i>
        <% end %>
          
      <% else %>
        <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
        <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
        <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
        <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_timeline.html.erb
<% recruits.each do |recruit| %>
	<div class="row justify-content-center" >
		<div class="col-md-6 my-3 box"style="border:solid 1px #DAA25A;height:40%;background-color:#FFFFF0;">
			<div class="row justify-content-center"style="height:50px;background-color:rgba(218,162,90,0.5)">
				<div class="col-2 mt-1" >
	      	<%= link_to user_path(recruit.user) do %>
	      	<%= attachment_image_tag recruit.user, :profile_image, format: 'jpeg'  ,class:"img-fluid rounded-circle" ,fallback: "no_image.jpg",size: "40x40" %><% end %></div>
	      	<div class="col-6 pl-0 align-self-center text-left ">
	      		<%= link_to user_path(recruit.user), class: "text-black" do %>
	      		<%= recruit.user.name %><% end %></div>
	      	<div class="col-md-4 align-self-center text-right">	<%= recruit.created_at.strftime('%Y/%m/%d') %></div>
			</div>
			
			<div class="col-md-6 ">
	    	<div class="row my-2 border-bottom">
				<div class="col-2 ">
					<p><i class="fas fa-heading"></i></p>
				</div>
				<div class="col-10 ">
					<p ><%= recruit.title %></p>
				</div>
				<div class="col-2">
				<p><i class="fas fa-map-marker-alt"></i></p>
				</div>
				<div class="col-10">
					<p><%= recruit.position %></p>
				</div>
				<div class="col-2">
					<p><i class="fas fa-yen-sign"></i></p>
				</div>
				<div class="col-10">
					<p> <%= recruit.reward %>円</p>
				</div>
				<div class="col-2">
					<p><i class="fas fa-info-circle"></i></p>
				</div>
				<div class="col-10">
					<p><%= recruit.body %></p>
				</div>
				</div>
				<!--コメント -->
				<div class="row mt-2">
					<div class="col">
						<p><i class="fas fa-comments"></i>
							<%= recruit.recruit_comments.count %>件
						</p>
					</div>
							<!-- いいね -->
					<div id="favorite_buttons_<%= recruit.id %>" class="col">
          	<%= render"favorites/favorite-btn", recruit: recruit %>
          </div>
				</div>

				 <!--diary showのボタン -->
				<div class="row my-3">
					<div class="col-12 text-center " >
						<%= link_to "詳細", recruit_path(recruit),class: "btn btn-dark btn-sm" %>
					</div>
				</div>
				
		</div>
		</div>
	</div>
<% end %>


<!-- kaminari -->
<div class="row justify-content-center my-2">
	<div class="col-6 bg-white">
		 <%= paginate recruits %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fencers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f2ca94efa4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://use.fontawesome.com/releases/v5.11.0/css/all.css" rel="stylesheet">
  </head>

  <body>
    <div class='wrap'>
      <div class='container-fluid'>
        <%= yield %>
      </div>
    </div>
  <footer>
  <%= render "layouts/footer" %>
  </footer>
  </body>
</html>